/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BebugTimes.java
 *
 * Created on 24-feb-2010, 20:53:40
 */

package jmanager.components;

import jmanager.JmanagerView;
import jmanager.dataResp;

/**
 *
 * @author paco
 */
public class BebugTimes extends javax.swing.JPanel {
	private String parentid;

	/** Creates new form BebugTimes */
	public BebugTimes() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		getTimesButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		freq = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		ctm = new javax.swing.JLabel();
		units = new javax.swing.JLabel();
		units2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		ctmin = new javax.swing.JLabel();
		units3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		ctmax = new javax.swing.JLabel();
		units4 = new javax.swing.JLabel();

		setBorder(javax.swing.BorderFactory.createEtchedBorder());

		getTimesButton.setText("Get Times");
		getTimesButton.setName("getTimesButton"); // NOI18N
		getTimesButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				getTimesButtonMouseClicked(evt);
			}
		});

		jLabel1.setText("Frequency: ");
		jLabel1.setName("jLabel1"); // NOI18N

		freq.setText("0");
		freq.setName("freq"); // NOI18N

		jLabel2.setText("Cycle time mean:");
		jLabel2.setName("jLabel2"); // NOI18N

		ctm.setText("0");
		ctm.setName("ctm"); // NOI18N

		units.setText("Hz");
		units.setName("units"); // NOI18N

		units2.setText("ms");
		units2.setName("units2"); // NOI18N

		jLabel3.setText("Cycle time min:");
		jLabel3.setName("jLabel3"); // NOI18N

		ctmin.setText("0");
		ctmin.setName("ctmin"); // NOI18N

		units3.setText("ms");
		units3.setName("units3"); // NOI18N

		jLabel4.setText("Cycle time max:");
		jLabel4.setName("jLabel4"); // NOI18N

		ctmax.setText("0");
		ctmax.setName("ctmax"); // NOI18N

		units4.setText("ms");
		units4.setName("units4"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(getTimesButton)
						.addGap(27, 27, 27)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1)
								.addComponent(jLabel2)
								.addComponent(jLabel3)
								.addComponent(jLabel4))
								.addGap(22, 22, 22)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(ctmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ctmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(ctm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(freq, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(units2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(units, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(units3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(units4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(57, 57, 57))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(21, 21, 21)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(getTimesButton)
								.addComponent(jLabel1)
								.addComponent(freq)
								.addComponent(units))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(ctm)
										.addComponent(units2))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(ctmin)
												.addComponent(units3))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(ctmax)
														.addComponent(units4))
														.addContainerGap(30, Short.MAX_VALUE))
		);
	}// </editor-fold>//GEN-END:initComponents

	private void getTimesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getTimesButtonMouseClicked
		if(parentid != null)
		{
			//resp = JmanagerView.root.getConnection().send("getDebugData:"+parentid+":");
			String data = new String(JmanagerView.root.getConnection().componentPrx.getDebugData(parentid));

			String[] values = data.split(":");

			freq.setText(values[0]);
			ctm.setText(values[1]);
			ctmax.setText(values[2]);
			ctmin.setText(values[3]);

		}
	}//GEN-LAST:event_getTimesButtonMouseClicked

	public void setParentId(String id)
	{
		parentid = id;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel ctm;
	private javax.swing.JLabel ctmax;
	private javax.swing.JLabel ctmin;
	private javax.swing.JLabel freq;
	private javax.swing.JButton getTimesButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel units;
	private javax.swing.JLabel units2;
	private javax.swing.JLabel units3;
	private javax.swing.JLabel units4;
	// End of variables declaration//GEN-END:variables
}
