/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComponentPerceptionPanel.java
 *
 * Created on 28-oct-2009, 13:08:37
 */
package jmanager.components;

import jmanager.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paco
 */
public class Body extends javax.swing.JPanel {

  private float _V=0.0f, _W=0.0f, _L=0.0f;

    /** Creates new form ComponentGTLocalization */
    public Body() {
        initComponents();
        //dataResp resp = JmanagerView.root.getConnection().send("Body:setVel:1.0:0.0:");

    }

    public void refresh() {

    }

    private void updateSpeed(){
    	JmanagerView.root.getConnection().bodyPrx.setVel(_V, _W, _L);
        //dataResp resp = JmanagerView.root.getConnection().send("Body:setVel:"+_V+":"+_W+":"+_L+":");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStop = new javax.swing.JButton();
        jButtonPoseInit = new javax.swing.JButton();
        jButtonLK = new javax.swing.JButton();
        jButtonRK = new javax.swing.JButton();
        jButtondoMove = new javax.swing.JButton();
        jTextFieldMove = new javax.swing.JTextField();
        jTextFieldFreq = new javax.swing.JTextField();
        jButtonFreq = new javax.swing.JButton();
        VSlider = new javax.swing.JSlider();
        LSlider = new javax.swing.JSlider();
        WSlider = new javax.swing.JSlider();
        jButtonLK1 = new javax.swing.JButton();
        jButtonRK1 = new javax.swing.JButton();
        jButtonLK2 = new javax.swing.JButton();
        jButtonRK2 = new javax.swing.JButton();
        jButtonLK3 = new javax.swing.JButton();
        jButtonLK4 = new javax.swing.JButton();
        jButtonLK5 = new javax.swing.JButton();
        jButtonLK6 = new javax.swing.JButton();
        jButtonLK7 = new javax.swing.JButton();
        jButtonLK8 = new javax.swing.JButton();
        jButtonLK9 = new javax.swing.JButton();
        jButtonLK10 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(330, 250));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(330, 250));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(Body.class);
        jButtonStop.setText(resourceMap.getString("jButtonStop.text")); // NOI18N
        jButtonStop.setName("jButtonStop"); // NOI18N
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopPressed(evt);
            }
        });

        jButtonPoseInit.setText(resourceMap.getString("jButtonPoseInit.text")); // NOI18N
        jButtonPoseInit.setName("jButtonPoseInit"); // NOI18N
        jButtonPoseInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoseInitActionPerformed(evt);
            }
        });

        jButtonLK.setText(resourceMap.getString("jButtonLK.text")); // NOI18N
        jButtonLK.setName("jButtonLK"); // NOI18N
        jButtonLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLKActionPerformed(evt);
            }
        });

        jButtonRK.setText(resourceMap.getString("jButtonRK.text")); // NOI18N
        jButtonRK.setActionCommand(resourceMap.getString("jButtonRK.actionCommand")); // NOI18N
        jButtonRK.setName("jButtonRK"); // NOI18N
        jButtonRK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRKActionPerformed(evt);
            }
        });

        jButtondoMove.setText(resourceMap.getString("jButtondoMove.text")); // NOI18N
        jButtondoMove.setName("jButtondoMove"); // NOI18N
        jButtondoMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondoMoveActionPerformed(evt);
            }
        });

        jTextFieldMove.setText(resourceMap.getString("jTextFieldMove.text")); // NOI18N
        jTextFieldMove.setName("jTextFieldMove"); // NOI18N

        jTextFieldFreq.setText(resourceMap.getString("jTextFieldFreq.text")); // NOI18N
        jTextFieldFreq.setName("jTextFieldFreq"); // NOI18N

        jButtonFreq.setText(resourceMap.getString("jButtonFreq.text")); // NOI18N
        jButtonFreq.setName("jButtonFreq"); // NOI18N
        jButtonFreq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFreqMouseClicked(evt);
            }
        });

        VSlider.setMinimum(-100);
        VSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        VSlider.setPaintTicks(true);
        VSlider.setToolTipText(resourceMap.getString("VSlider.toolTipText")); // NOI18N
        VSlider.setValue(0);
        VSlider.setName("VSlider"); // NOI18N
        VSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                VSliderMouseReleased(evt);
            }
        });

        LSlider.setMinimum(-100);
        LSlider.setPaintTicks(true);
        LSlider.setValue(0);
        LSlider.setName("LSlider"); // NOI18N
        LSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LSliderMouseReleased(evt);
            }
        });

        WSlider.setMinimum(-100);
        WSlider.setPaintTicks(true);
        WSlider.setValue(0);
        WSlider.setName("WSlider"); // NOI18N
        WSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                WSliderMouseReleased(evt);
            }
        });

        jButtonLK1.setText(resourceMap.getString("jButtonLK1.text")); // NOI18N
        jButtonLK1.setName("jButtonLK1"); // NOI18N
        jButtonLK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK1ActionPerformed(evt);
            }
        });

        jButtonRK1.setText(resourceMap.getString("jButtonRK1.text")); // NOI18N
        jButtonRK1.setActionCommand(resourceMap.getString("jButtonRK1.actionCommand")); // NOI18N
        jButtonRK1.setName("jButtonRK1"); // NOI18N
        jButtonRK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRK1ActionPerformed(evt);
            }
        });

        jButtonLK2.setText(resourceMap.getString("jButtonLK2.text")); // NOI18N
        jButtonLK2.setName("jButtonLK2"); // NOI18N
        jButtonLK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK2ActionPerformed(evt);
            }
        });

        jButtonRK2.setText(resourceMap.getString("jButtonRK2.text")); // NOI18N
        jButtonRK2.setName("jButtonRK2"); // NOI18N
        jButtonRK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRK2ActionPerformed(evt);
            }
        });

        jButtonLK3.setText(resourceMap.getString("jButtonLK3.text")); // NOI18N
        jButtonLK3.setName("jButtonLK3"); // NOI18N
        jButtonLK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK3ActionPerformed(evt);
            }
        });

        jButtonLK4.setText(resourceMap.getString("jButtonLK4.text")); // NOI18N
        jButtonLK4.setName("jButtonLK4"); // NOI18N
        jButtonLK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK4ActionPerformed(evt);
            }
        });

        jButtonLK5.setText(resourceMap.getString("jButtonLK5.text")); // NOI18N
        jButtonLK5.setName("jButtonLK5"); // NOI18N
        jButtonLK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK5ActionPerformed(evt);
            }
        });

        jButtonLK6.setText(resourceMap.getString("jButtonLK6.text")); // NOI18N
        jButtonLK6.setName("jButtonLK6"); // NOI18N
        jButtonLK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK6ActionPerformed(evt);
            }
        });

        jButtonLK7.setText(resourceMap.getString("jButtonLK7.text")); // NOI18N
        jButtonLK7.setName("jButtonLK7"); // NOI18N
        jButtonLK7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK7ActionPerformed(evt);
            }
        });

        jButtonLK8.setText(resourceMap.getString("jButtonLK8.text")); // NOI18N
        jButtonLK8.setName("jButtonLK8"); // NOI18N
        jButtonLK8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK8ActionPerformed(evt);
            }
        });

        jButtonLK9.setText(resourceMap.getString("jButtonLK9.text")); // NOI18N
        jButtonLK9.setName("jButtonLK9"); // NOI18N
        jButtonLK9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK9ActionPerformed(evt);
            }
        });

        jButtonLK10.setText(resourceMap.getString("jButtonLK10.text")); // NOI18N
        jButtonLK10.setName("jButtonLK10"); // NOI18N
        jButtonLK10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLK10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPoseInit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtondoMove)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldMove, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonFreq)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonLK1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jButtonLK2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jButtonLK3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jButtonLK5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jButtonLK7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jButtonLK9, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonLK8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(jButtonLK4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(jButtonRK2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(jButtonRK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonRK1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(jButtonLK6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(jButtonLK10, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))))
                            .addComponent(WSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtondoMove)
                                    .addComponent(jTextFieldMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonFreq)
                                    .addComponent(jTextFieldFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonLK2)
                                    .addComponent(jButtonRK2)))
                            .addComponent(VSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(WSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonLK)
                                    .addComponent(jButtonRK))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonRK1)
                                    .addComponent(jButtonLK1)))
                            .addComponent(LSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLK3)
                            .addComponent(jButtonLK4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLK5)
                            .addComponent(jButtonLK6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonStop)
                            .addComponent(jButtonPoseInit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLK7)
                    .addComponent(jButtonLK8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLK9)
                    .addComponent(jButtonLK10))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPoseInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPoseInitActionPerformed
        	JmanagerView.root.getConnection().bodyPrx.poseInit();
            //dataResp resp = JmanagerView.root.getConnection().send("Body:poseInit:");
       
    }//GEN-LAST:event_jButtonPoseInitActionPerformed

    private void jButtonLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLKActionPerformed
         	JmanagerView.root.getConnection().bodyPrx.doMove("TXTFWDRR");
            //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:LFOOT:0.0:0.0:0.0:");
        
    }//GEN-LAST:event_jButtonLKActionPerformed

    private void jButtonRKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRKActionPerformed
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTFWDRL");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        
    }//GEN-LAST:event_jButtonRKActionPerformed

    private void jButtondoMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondoMoveActionPerformed
        	JmanagerView.root.getConnection().bodyPrx.doMove(jTextFieldMove.getText());
            //dataResp resp = JmanagerView.root.getConnection().send("Body:doMove:"+jTextFieldMove.getText()+":");
    }//GEN-LAST:event_jButtondoMoveActionPerformed

    private void jButtonFreqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFreqMouseClicked
              //dataResp resp = JmanagerView.root.getConnection().send("Body:setFreq:"+jTextFieldFreq.getText()+":");
        
    }//GEN-LAST:event_jButtonFreqMouseClicked

    private void buttonStopPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopPressed
            //dataResp resp = JmanagerView.root.getConnection().send("Body:stop:");
            
            _V = _W = _L = 0.001f;
            
            updateSpeed();

            VSlider.setValue(0);
            WSlider.setValue(0);
            LSlider.setValue(0);
       
}//GEN-LAST:event_buttonStopPressed

    private void VSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VSliderMouseReleased

         _V = ((float)VSlider.getValue())/100.0f;

         updateSpeed();
    }//GEN-LAST:event_VSliderMouseReleased

    private void LSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSliderMouseReleased

        _L = ((float)LSlider.getValue())/100.0f;

         updateSpeed();

    }//GEN-LAST:event_LSliderMouseReleased

    private void WSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WSliderMouseReleased
         _W = ((float)WSlider.getValue())/100.0f;

         updateSpeed();

    }//GEN-LAST:event_WSliderMouseReleased

    private void jButtonLK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK1ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTFWNR");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK1ActionPerformed

    private void jButtonRK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRK1ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTFWNL");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonRK1ActionPerformed

    private void jButtonLK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK2ActionPerformed
        
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTFWSTR");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK2ActionPerformed

    private void jButtonRK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRK2ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTFWSTL");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonRK2ActionPerformed

    private void jButtonLK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK3ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTSIDE2RI");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK3ActionPerformed

    private void jButtonLK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK4ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTSIDE2LI");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK4ActionPerformed

    private void jButtonLK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK5ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTSIDE2RSI");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK5ActionPerformed

    private void jButtonLK6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK6ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTSIDE2LSI");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK6ActionPerformed

    private void jButtonLK7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK7ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTSIDE2RO");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK7ActionPerformed

    private void jButtonLK8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK8ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTSIDE2LO");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK8ActionPerformed

    private void jButtonLK9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK9ActionPerformed
        
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTOB2R");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK9ActionPerformed

    private void jButtonLK10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLK10ActionPerformed
       
       	JmanagerView.root.getConnection().bodyPrx.doMove("TXTOB2L");
    	   //dataResp resp = JmanagerView.root.getConnection().send("Body:doKick:RFOOT:0.0:0.0:0.0:");
        

    }//GEN-LAST:event_jButtonLK10ActionPerformed
/**/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider LSlider;
    private javax.swing.JSlider VSlider;
    private javax.swing.JSlider WSlider;
    private javax.swing.JButton jButtonFreq;
    private javax.swing.JButton jButtonLK;
    private javax.swing.JButton jButtonLK1;
    private javax.swing.JButton jButtonLK10;
    private javax.swing.JButton jButtonLK2;
    private javax.swing.JButton jButtonLK3;
    private javax.swing.JButton jButtonLK4;
    private javax.swing.JButton jButtonLK5;
    private javax.swing.JButton jButtonLK6;
    private javax.swing.JButton jButtonLK7;
    private javax.swing.JButton jButtonLK8;
    private javax.swing.JButton jButtonLK9;
    private javax.swing.JButton jButtonPoseInit;
    private javax.swing.JButton jButtonRK;
    private javax.swing.JButton jButtonRK1;
    private javax.swing.JButton jButtonRK2;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtondoMove;
    private javax.swing.JTextField jTextFieldFreq;
    private javax.swing.JTextField jTextFieldMove;
    // End of variables declaration//GEN-END:variables


    private void printResp(dataResp r) {

        //sbyte[] util = new byte[r.size];

        if (r.size < 500) {

            System.out.println("Respuesta: [" + new String(r.data) + "] (" + r.size + ")");
        } else {
            System.out.println("Respuesta: [X] (" + r.size + ")");
        }

    }

}