/*
 * LogExport.java
 *
 * Created on 03-ago-2011, 12:05:55
 */
package jmanager.components;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import jmanager.JmanagerView;
import jmanager.components.log.LogHeader;

/**
 *
 * @author carlos
 */
public class LogExport extends javax.swing.JPanel {

    /** Creates new form LogExport */
    public LogExport( String filename ) {
       
         initComponents();
         
         toExport = new ArrayList();
        
        try {
            logHeader = new LogHeader(filename);
            logHeader.readHeader();
                        
            AvailableLabelsList.setListData(logHeader.getLabels().toArray());       
            labels2ExportList.setListData(toExport.toArray());
         

        } catch (FileNotFoundException ex) {
            Logger.getLogger(JmanagerView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JmanagerView.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        availablesLabel = new javax.swing.JLabel();
        toExportLabel = new javax.swing.JLabel();
        UpButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvailableLabelsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        labels2ExportList = new javax.swing.JList();
        exportButton = new javax.swing.JButton();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        availablesLabel.setText("Available labels");
        availablesLabel.setName("availablesLabel"); // NOI18N

        toExportLabel.setText("To be exported");
        toExportLabel.setName("toExportLabel"); // NOI18N

        UpButton.setText("^");
        UpButton.setName("UpButton"); // NOI18N
        UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButtonActionPerformed(evt);
            }
        });

        downButton.setText("v");
        downButton.setMaximumSize(new java.awt.Dimension(38, 27));
        downButton.setMinimumSize(new java.awt.Dimension(38, 27));
        downButton.setName("downButton"); // NOI18N
        downButton.setPreferredSize(new java.awt.Dimension(38, 27));
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("X");
        RemoveButton.setName("RemoveButton"); // NOI18N
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        RightButton.setText("->");
        RightButton.setName("RightButton"); // NOI18N
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        AvailableLabelsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        AvailableLabelsList.setName("AvailableLabelsList"); // NOI18N
        jScrollPane1.setViewportView(AvailableLabelsList);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        labels2ExportList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        labels2ExportList.setName("labels2ExportList"); // NOI18N
        jScrollPane2.setViewportView(labels2ExportList);

        exportButton.setText("Export");
        exportButton.setName("exportButton"); // NOI18N
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(RightButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(availablesLabel)
                        .addGap(48, 48, 48)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(UpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(exportButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(toExportLabel)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availablesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toExportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpButton)
                    .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(exportButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        toExport.addAll(Arrays.asList(AvailableLabelsList.getSelectedValues()));
        labels2ExportList.setListData(toExport.toArray());
    }//GEN-LAST:event_RightButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        for (int i = 0; i < labels2ExportList.getSelectedIndices().length; i++) {
            toExport.remove(labels2ExportList.getSelectedIndices()[i] - i);            
        }
        labels2ExportList.setListData(toExport.toArray());
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButtonActionPerformed
        if ( (labels2ExportList.getSelectedIndex() > 0) && (labels2ExportList.getSelectedIndices().length == 1) ) {
            Collections.swap(toExport, labels2ExportList.getSelectedIndex(), labels2ExportList.getSelectedIndex() - 1);
            labels2ExportList.setListData(toExport.toArray());
        }
    }//GEN-LAST:event_UpButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        if ( (labels2ExportList.getSelectedIndex() < toExport.size() - 1) && (labels2ExportList.getSelectedIndices().length == 1) ) {
            Collections.swap(toExport, labels2ExportList.getSelectedIndex(), labels2ExportList.getSelectedIndex() + 1);
            labels2ExportList.setListData(toExport.toArray());
        }
    }//GEN-LAST:event_downButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        if (toExport.size() > 0) {
                        
             // Choose the log file
            JFileChooser chooser = new JFileChooser();
            //FileNameExtensionFilter filter = new FileNameExtensionFilter("Log files", "log");
            //chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                logHeader.readFilteredBody(toExport);
                logHeader.toDisk(chooser.getSelectedFile().getAbsolutePath());
                
                // Close window
                setVisible(false);                
            }
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AvailableLabelsList;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JButton UpButton;
    private javax.swing.JLabel availablesLabel;
    private javax.swing.JButton downButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList labels2ExportList;
    private javax.swing.JLabel toExportLabel;
    // End of variables declaration//GEN-END:variables

    private LogHeader logHeader;
    ArrayList toExport;
}
