/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package jmanager.components;

import jmanager.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;

import java.io.File;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * @author rbenitez
 */
public class Movie extends javax.swing.JPanel implements java.beans.Customizer {

	private Object bean;

	/** Creates new customizer Movie */
	public Movie() {
		initComponents();
	}

	public void setObject(Object bean) {
		this.bean = bean;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the FormEditor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PlayMovie = new javax.swing.JButton();
        StopMovie = new javax.swing.JButton();
        LoadMovie = new javax.swing.JButton();
        txtFileMovie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fichmov = new javax.swing.JTextArea();
        SaveFile = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        lineStart = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        fichmovPos = new javax.swing.JTextArea();
        PauseMovie = new javax.swing.JButton();
        SendFileRobot = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CreateMovie = new javax.swing.JButton();
        PreviusBreakpoint = new javax.swing.JButton();
        NextBreakpoint = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        PlayMovie.setText("Play");
        PlayMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayMovieActionPerformed(evt);
            }
        });
        PlayMovie.setBounds(0, 150, 70, 40);
        jLayeredPane1.add(PlayMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        StopMovie.setText("Stop");
        StopMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopMovieActionPerformed(evt);
            }
        });
        StopMovie.setBounds(120, 150, 42, 40);
        jLayeredPane1.add(StopMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LoadMovie.setText("Load Movie");
        LoadMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadMovieActionPerformed(evt);
            }
        });
        LoadMovie.setBounds(0, 20, 110, 30);
        jLayeredPane1.add(LoadMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtFileMovie.setColumns(5);
        txtFileMovie.setEditable(false);
        txtFileMovie.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtFileMovie.setBounds(120, 20, 170, 27);
        jLayeredPane1.add(txtFileMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fichmov.setColumns(20);
        fichmov.setRows(5);
        jScrollPane1.setViewportView(fichmov);

        jScrollPane1.setBounds(350, 10, 350, 360);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SaveFile.setText("Save");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        SaveFile.setBounds(300, 380, 44, 29);
        jLayeredPane1.add(SaveFile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setText("Start in line:");
        jLabel27.setBounds(0, 100, 80, 17);
        jLayeredPane1.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lineStart.setColumns(5);
        lineStart.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lineStart.setText("1");
        lineStart.setBounds(90, 90, 70, 27);
        jLayeredPane1.add(lineStart, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setHorizontalScrollBar(null);

        fichmovPos.setColumns(20);
        fichmovPos.setRows(5);
        jScrollPane2.setViewportView(fichmovPos);

        jScrollPane2.setBounds(290, 10, 60, 360);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PauseMovie.setText("Pause");
        PauseMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseMovieActionPerformed(evt);
            }
        });
        PauseMovie.setBounds(70, 150, 51, 40);
        jLayeredPane1.add(PauseMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SendFileRobot.setText("Send File to Robot");
        SendFileRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFileRobotActionPerformed(evt);
            }
        });
        SendFileRobot.setBounds(360, 380, 130, 29);
        jLayeredPane1.add(SendFileRobot, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Language for the script:\nMovement:\nmov namemov\n\nMusic:\nmusic path/file.mp3\n\nTalk:\ntalk file path/file.txt\ntalk text \"text to say\" \ntalk language Spanish / English\ntalk voice Heather22Enhanced\ntalk volume val (0-100)\n\nWalk:\nwalk Vx Vy Vz (For Stop: walk 0 0 0 )\n\nWait\nwait task NameTask (music,mov,talk)\nwait time 3 (time in second)\nwait press NameButton (left,right,chest)\n\nStop:\nstop task NameTask (music,talk)\nstop task all\n\nStiffness:\nstiffness on/off (Attention! Never put this command if not written before a command to the robot is sitting)\n\nLeds:\nled led_id modo color\n\nled_id\n0 -> AllLeds\n1 -> EarLeds\n2 -> ChestLeds\n3 -> LeftFootLeds\n4 -> RightFootLeds\n5 -> FaceLeds\n6 -> LeftFaceLeds\n7 -> RightFaceLeds\n8 -> FeetLeds\n\nModo:\n0 -> OFF\n1 -> ON\n2 -> AUTO (No color selection)\n\nColor:\n0 -> NOCOLOR\n1 -> RED\n2 -> BLUE\n3 -> GREEN\n4 -> YELLOW\n5 -> WHITE\n6 -> ORANGE\n\nBreakpoint:\nbreakpoint (Points to skip a block of statements)");
        jTextArea1.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea1);

        jScrollPane3.setBounds(720, 10, 360, 430);
        jLayeredPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CreateMovie.setText("Create Movie");
        CreateMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMovieActionPerformed(evt);
            }
        });
        CreateMovie.setBounds(0, 50, 110, 30);
        jLayeredPane1.add(CreateMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PreviusBreakpoint.setText("Previus BreakPoint");
        PreviusBreakpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviusBreakpointActionPerformed(evt);
            }
        });
        PreviusBreakpoint.setBounds(0, 200, 140, 30);
        jLayeredPane1.add(PreviusBreakpoint, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NextBreakpoint.setText("Next BreakPoint");
        NextBreakpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBreakpointActionPerformed(evt);
            }
        });
        NextBreakpoint.setBounds(0, 240, 140, 30);
        jLayeredPane1.add(NextBreakpoint, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void LoadMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadMovieActionPerformed
		// TODO add your handling code here:
		final JFileChooser fc = new JFileChooser();
		int returnVal = fc.showOpenDialog(Movie.this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file =fc.getSelectedFile();
			txtFileMovie.setColumns(file.toString().length());
			txtFileMovie.setText(file.toString());
			try{
				File archivo = null;
				FileReader fr = null;
				BufferedReader br = null;
				archivo = new File(file.toString());

				fr = new FileReader(archivo);
				br = new BufferedReader(fr);

				fichmov.setText("");
				String linea;
				int cont=1;
				while ((linea=br.readLine()) != null){
					if (fichmov.getText().equals("")){
						fichmov.setText (linea);
						fichmovPos.setText(String.valueOf(cont));
					}
					else{
						fichmov.setText( fichmov.getText() + "\n" + linea );
						fichmovPos.setText(fichmovPos.getText() + "\n" + String.valueOf(cont));
					}

					cont++;
				}

				lineStart.setText("1");

				//Send the SetFileMP3 to robot
				JmanagerView.root.getConnection().moviePrx.setFile(file.toString());
				//dataResp resp = JmanagerView.root.getConnection().send("movie:setFile:"+file.toString()+":");

			} catch(Exception e){

				JOptionPane.showMessageDialog(this,"Check the file","Error",JOptionPane.ERROR_MESSAGE);

				//e.printStackTrace();
			}

		} else {
			System.out.println("Open command cancelled by user.");
		}

	}//GEN-LAST:event_LoadMovieActionPerformed

	private void PlayMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayMovieActionPerformed
		// TODO add your handling code here:
		/*     dataResp resp = JmanagerView.root.getConnection().send("playPress:");
            try {
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Movie.class.getName()).log(Level.SEVERE, null, ex);
            }*/
		//if (ActivationCheckBox.isSelected()) {
			JmanagerView.root.getConnection().moviePrx.playPress(Integer.parseInt(lineStart.getText()));
			//dataResp resp = JmanagerView.root.getConnection().send("movie:playPress:"+lineStart.getText()+":");

		//}
	}//GEN-LAST:event_PlayMovieActionPerformed

	private void StopMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopMovieActionPerformed
		// TODO add your handling code here:
		JmanagerView.root.getConnection().moviePrx.stop();
		//dataResp resp = JmanagerView.root.getConnection().send("movie:stopPress:");
		//printResp(resp);
		/*resp = JmanagerView.root.getConnection().send("pause:Movie:");
            printResp(resp);*/
	}//GEN-LAST:event_StopMovieActionPerformed


	private boolean SaveFile(){
		BufferedWriter bufferedWriter = null;

		try {
			bufferedWriter = new  BufferedWriter(new FileWriter(txtFileMovie.getText()));
			String Line = fichmov.getText();
			System.out.println(Line);
			bufferedWriter.write(Line);
			System.out.println("Fin, en file: " + txtFileMovie.getText());
			return true;
		}
		catch(Exception e){


			return false;

			//e.printStackTrace();
		}
		finally {
			//Close the BufferedWriter
			try {
				if (bufferedWriter != null) {
					bufferedWriter.flush();
					bufferedWriter.close();
					return true;
				}
			} catch (IOException ex) {
				ex.printStackTrace();
				return false;
			}
		}

	}

	private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
		// TODO add your handling code here:

		if (!(SaveFile())) JOptionPane.showMessageDialog(this,"Check the file","Error",JOptionPane.ERROR_MESSAGE);

	}//GEN-LAST:event_SaveFileActionPerformed

	private void PauseMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseMovieActionPerformed
		// TODO add your handling code here:

		//dataResp resp = JmanagerView.root.getConnection().send("movie:pausePress:");
		String num = new String(String.valueOf(JmanagerView.root.getConnection().moviePrx.pausePress())) ;
		System.out.print("Num:" + num);
		lineStart.setText(num);

	}//GEN-LAST:event_PauseMovieActionPerformed

	private void SendFileRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFileRobotActionPerformed
		// TODO add your handling code here:
		System.out.print("File" + txtFileMovie.getText());
		if (!(txtFileMovie.getText().equals(""))){
			//dataResp resp = JmanagerView.root.getConnection().send("movie:sendFile:"+ txtFileMovie.getText() + ":" + fichmov.getText()+":");
			//String respu = new String(resp.data);
			if (!JmanagerView.root.getConnection().moviePrx.saveFile(txtFileMovie.getText(), fichmov.getText()))
				JOptionPane.showMessageDialog(this,"Check the path file","Error path file",JOptionPane.ERROR_MESSAGE);
			else{
				JOptionPane.showMessageDialog(this,"Send File OK","OK",JOptionPane.INFORMATION_MESSAGE);
				SaveFile();

			}
		}else
			JOptionPane.showMessageDialog(this,"Check the path file","Error Path File",JOptionPane.ERROR_MESSAGE);
		lineStart.setText("1");
	}//GEN-LAST:event_SendFileRobotActionPerformed

	private void CreateMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMovieActionPerformed
		// TODO add your handling code here:
		final JFileChooser fc = new JFileChooser();
		int returnVal = fc.showSaveDialog(Movie.this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file =fc.getSelectedFile();
			txtFileMovie.setText(file.toString());
		}
	}//GEN-LAST:event_CreateMovieActionPerformed

	private void PreviusBreakpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviusBreakpointActionPerformed
		// TODO add your handling code here:
		//dataResp resp = JmanagerView.root.getConnection().send("movie:previousPress:");
		String num = new String(String.valueOf(JmanagerView.root.getConnection().moviePrx.previousPress())) ;
		System.out.print("Num:" + num);
		lineStart.setText(num);
	}//GEN-LAST:event_PreviusBreakpointActionPerformed

	private void NextBreakpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBreakpointActionPerformed
		// TODO add your handling code here:
		//dataResp resp = JmanagerView.root.getConnection().send("movie:nextPress:");
		String num = new String(String.valueOf(JmanagerView.root.getConnection().moviePrx.nextPress())) ;
		System.out.print("Num:" + num);
		lineStart.setText(num);
	}//GEN-LAST:event_NextBreakpointActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateMovie;
    private javax.swing.JButton LoadMovie;
    private javax.swing.JButton NextBreakpoint;
    private javax.swing.JButton PauseMovie;
    private javax.swing.JButton PlayMovie;
    private javax.swing.JButton PreviusBreakpoint;
    private javax.swing.JButton SaveFile;
    private javax.swing.JButton SendFileRobot;
    private javax.swing.JButton StopMovie;
    private javax.swing.JTextArea fichmov;
    private javax.swing.JTextArea fichmovPos;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lineStart;
    private javax.swing.JTextField txtFileMovie;
    // End of variables declaration//GEN-END:variables

	private void printResp(dataResp r) {

		//sbyte[] util = new byte[r.size];

		if (r.size < 500) {

			System.out.println("Respuesta: [" + new String(r.data) + "] (" + r.size + ")");
		} else {
			System.out.println("Respuesta: [X] (" + r.size + ")");
		}

	}


}
