/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComponentPerceptionPanel.java
 *
 * Created on 28-oct-2009, 13:08:37
 */
package jmanager.components;

import jmanager.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paco
 */
public class pruebag2gpos extends javax.swing.JPanel {

	/** Creates new form ComponentGTLocalization */
	public pruebag2gpos() {
		initComponents();
	}

	public void refresh() {

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FieldLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(330, 250));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(330, 250));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(pruebag2gpos.class);
        FieldLabel.setBackground(resourceMap.getColor("FieldLabel.background")); // NOI18N
        FieldLabel.setForeground(resourceMap.getColor("FieldLabel.foreground")); // NOI18N
        FieldLabel.setIcon(resourceMap.getIcon("FieldLabel.icon")); // NOI18N
        FieldLabel.setDoubleBuffered(true);
        FieldLabel.setName("FieldLabel"); // NOI18N
        FieldLabel.setOpaque(true);
        FieldLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(FieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(FieldLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void FieldLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldLabelMouseClicked
		double mx = evt.getX();
		double my = evt.getY();
		double centerx, centery;

		double fheight = 5350.0;
		double fwidth  = 7350.0;

		double Ax, Ay;

		centerx = FieldLabel.getWidth()/2.0;
		centery = FieldLabel.getHeight()/2.0;

		Ax = (mx - centerx)/(FieldLabel.getWidth()/2.0);
		Ay = (my - centery)/(FieldLabel.getHeight()/2.0);

		double x, y;

		//Change to official coordinates
			x = Ax * (fwidth/2.0);
			y = -Ay * (fheight/2.0);

                        //JmanagerView.root.getConnection().pruebag2gposPrx.setGoalPos(x,y);

	}//GEN-LAST:event_FieldLabelMouseClicked
	/**/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FieldLabel;
    // End of variables declaration//GEN-END:variables
}