/*
 * Frame.java
 *
 * Created on 13-ene-2010, 19:26:44
 */
package jmanager.VICODE;

import javax.swing.JTextField;

/**
 *
 * @author paco
 */
public class TransitionCodeFrame extends javax.swing.JFrame {

	private Transition transition = null;
	private State sourceState = null;

	/** Creates new form Frame */
	public TransitionCodeFrame() {
		initComponents();
		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        msgLabel = new javax.swing.JLabel();
        timerCheckBox = new javax.swing.JCheckBox();
        priorityLabel = new javax.swing.JLabel();
        decreasePriorityButton = new javax.swing.JButton();
        increasePriorityButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TransitionCodeFrame.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        idTextField.setName("idTextField"); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jEditorPane1.setBackground(resourceMap.getColor("jEditorPane1.background")); // NOI18N
        jEditorPane1.setName("jEditorPane1"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        msgLabel.setText(resourceMap.getString("msgLabel.text")); // NOI18N
        msgLabel.setName("msgLabel"); // NOI18N

        timerCheckBox.setText(resourceMap.getString("timerCheckBox.text")); // NOI18N
        timerCheckBox.setName("timerCheckBox"); // NOI18N
        timerCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timerStateChanged(evt);
            }
        });

        priorityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priorityLabel.setText(resourceMap.getString("priorityLabel.text")); // NOI18N
        priorityLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        priorityLabel.setName("priorityLabel"); // NOI18N

        decreasePriorityButton.setText(resourceMap.getString("decreasePriorityButton.text")); // NOI18N
        decreasePriorityButton.setName("decreasePriorityButton"); // NOI18N
        decreasePriorityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decreasePriorityButtonMouseClicked(evt);
            }
        });

        increasePriorityButton.setText(resourceMap.getString("increasePriorityButton.text")); // NOI18N
        increasePriorityButton.setName("increasePriorityButton"); // NOI18N
        increasePriorityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                increasePriorityButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timerCheckBox)
                        .addGap(29, 29, 29)
                        .addComponent(decreasePriorityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(increasePriorityButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timerCheckBox)
                        .addComponent(priorityLabel)
                        .addComponent(increasePriorityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(decreasePriorityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
		if (transition != null) {
			//System.out.println("La transición es: " + transition.getId());
			if (! transition.setId(idTextField.getText().trim())) {
				msgLabel.setText("Transition already exists");
			} else {
				msgLabel.setText("");
			}
		}
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void decreasePriorityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreasePriorityButtonMouseClicked
		sourceState.changeTransitionPriorities(transition.getPriority(), transition.getPriority() - 1);
		//OJO el contador se actualiza desde Transition.setPriority(p);
			//priorityLabel.setText(new Integer(transition.getPriority()).toString());
    }//GEN-LAST:event_decreasePriorityButtonMouseClicked

    private void increasePriorityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increasePriorityButtonMouseClicked
		sourceState.changeTransitionPriorities(transition.getPriority(), transition.getPriority() + 1);
    }//GEN-LAST:event_increasePriorityButtonMouseClicked

    private void timerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timerStateChanged
		transition.setTimer(timerCheckBox.isSelected());
    }//GEN-LAST:event_timerStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decreasePriorityButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton increasePriorityButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JCheckBox timerCheckBox;
    // End of variables declaration//GEN-END:variables

	public void setIdTextField(String id) {
		idTextField.setText(id);
	}

	public void setTransition(Transition aThis) {
		transition = aThis;
	}

	public String getCode() {
		return jEditorPane1.getText();
	}

	public JTextField getIdTextField() {
		return idTextField;
	}

	public void setCode(String code) {
		jEditorPane1.setText(code);
	}

	public boolean isTimerDriven() {
		return timerCheckBox.isSelected();
	}

	public void setPriorityLabel() {
		priorityLabel.setText(new Integer(transition.getPriority()).toString());
	}

	public void setTimerCheckBox() {
		timerCheckBox.setSelected(transition.getTimer());
	}

	public void setSourceState(State state) {
		sourceState = state;
	}
}
